### ISSUE TITLE
FileNotFoundError error

### ISSUE THREAD

**Issue by ctroupin** [euroargodev/argopy#71] opened 2020-11-28 21:13 UTC
## MCVE Code Sample

```python
ds = argo_loader.region([8.14516, 9.9408, 40.716401, 43.31488, 
                         0., 2000., '2015-04-01', '2015-04-30'])
ds.to_xarray()

FileNotFoundError: https://www.ifremer.fr/erddap/tabledap/ArgoFloats.nc?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude>=8.14516&longitude<=9.9408&latitude>=40.716401&latitude<=43.31488&pres>=0.0&pres<=2000.0&time>=1427846400.0&time<=1430352000.0&distinct()&orderBy("time,pres")
```

#### Expected Output

I'm not sure here, but if there is no file for the period/domain selected, I should get a `ValueError`, no?
Here there is the path of a file, but this file is not found.

Of course I can use a `try... except` to avoid the problem.

#### Versions

<details><summary>Output of `argopy.show_versions()`</summary>

INSTALLED VERSIONS
------------------
commit: None
python: 3.8.0 (default, Dec 10 2019, 10:35:48) 
[GCC 5.4.0 20160609]
python-bits: 64
OS: Linux
OS-release: 4.15.0-123-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.10.5
libnetcdf: 4.6.3

argopy: 0.1.6
xarray: 0.16.1
pandas: 1.1.4
numpy: 1.19.4
scipy: 1.5.4
fsspec: 0.8.3
erddapy: 0.7.2
netCDF4: 1.5.4
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: 2.4.0
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.30.0
distributed: 2.30.0
matplotlib: 3.3.2
cartopy: 0.18.0
seaborn: 0.11.0
numbagg: None
gsw: 3.4.0
setuptools: 49.6.0
pip: 20.2.3
conda: None
pytest: 6.1.1
IPython: 7.18.1
sphinx: 3.3.1

</details>

**Comment by ocefpaf** [comment] 2020-11-28 22:52
If you remove the `<=` time constraint you'll notice that you [don't have data inside that time interval](https://www.ifremer.fr/erddap/tabledap/ArgoFloats.htmlTable?data_mode,latitude,longitude,position_qc,time,time_qc,direction,platform_number,cycle_number,config_mission_number,vertical_sampling_scheme,pres,temp,psal,pres_qc,temp_qc,psal_qc,pres_adjusted,temp_adjusted,psal_adjusted,pres_adjusted_qc,temp_adjusted_qc,psal_adjusted_qc,pres_adjusted_error,temp_adjusted_error,psal_adjusted_error&longitude%3E=8.14516&longitude%3C=9.9408&latitude%3E=40.716401&latitude%3C=43.31488&pres%3E=0.0&pres%3C=2000.0&time%3E=1427846400&distinct()&orderBy(%22time,pres%22)).

Latest `erddapy` is a bit smarter with that kind of error but I'm not sure if argopy wraps that failure and hinders the message. I'll check the code later.

PS: Closing this b/c this is not a problem with `argopy`. We can do nicer error messages but the problem is the query.

**Closed by ocefpaf** 2020-11-28 22:52 UTC

**Comment by ctroupin** [comment] 2020-11-30 09:43
Thanks for the explanations @ocefpaf .

**Comment by ocefpaf** [comment] 2020-11-30 11:09
> Thanks for the explanations @ocefpaf .

BTW, just in case it was not clear. While the problem is not `argopy` the problem is also not the user. The error message we are passing is not informative enough!

Maybe we should either re-open or open a new one with that title. (In hindsight I closed this prematurely.)
